title: Github tutorial for pages
author: benichka
email: pleasedontspamme@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  it's the best website ever.

# social links
twitter_username: ben1chka
github_username:  benichka

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
